name: Deploying my random quotes site

on:
  # Runs on pushes targeting the default branch
  workflow_dispatch:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      
    #set up node js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

    # Install dependencies and build the project
      - name: Install dependencies
        run: npm install

    # Build the project
      - name: Build
        run: npm run build

    # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          # publish_branch: gh-pages
          # publish_repo: ${{ github.repository }}
          # force_orphan: true